id: P005609
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:06:47.476719
source_metadata:
  id: bdr:W1KG9031
  title: མདོ་སྡེ་རྒྱན་གྱི་རྣམ་བཤད།
  author: ''
  volumes:
    c0ccd23da44a4bf9b8a5d151d16e2a93:
      image_group_id: I1KG9054
      title: ''
      volume_number: 1
      total_pages: 596
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
